171 SETUP file upload system for images or other files
abdelh17/Quolance pull request #201
Opened 2024-12-21 23:25 UTC by SSathu

- Basic Setup for File Upload
- Able to upload images, pdf and videos
- Update as needed for further functionalities

2024-12-21 23:28 UTC, NotMalek submitted a review, later dismissed
Tested, everything works well

2024-12-21 23:35 UTC, FehamIsmail approved these changes
Looks good and tested it too

2024-12-22 00:15 UTC, abdelh17 requested changes
Try to add tests plz

2024-12-22 00:15 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/FileServiceImpl.java
> +            throw new RuntimeException(e);
ApiException so we can see it.

2024-12-22 00:15 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/configs/CloudinaryConfig.java
> +    private final String cloudName = System.getenv("CLOUDINARY_CLOUD_NAME");
use `@Value` like in AdminInitializer instead of `System.getenv`

2024-12-22 00:15 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/entities/FileEntity.java
why not Getter and Setter annotation on the class itself instead of each field

2024-12-22 00:15 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/FileService.java
> +    //List<FileUpload> (Long userId);
remove commented line

2024-12-22 00:15 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/controllers/FileController.java
Add Swagger documentation, see other controllers. At least to have a description/title on endpoints

2024-12-22 02:11 UTC, abdelh17 approved these changes

2024-12-22 02:22 UTC, abdelh17 approved these changes

2024-12-22 02:53 UTC, NotMalek approved these changes

2024-12-22 02:53 UTC, merged