BE #125 blog controllers
abdelh17/Quolance pull request #211
Opened 2024-12-28 00:59 UTC by Itek01

- Updated Postman for Blog Posts and Threads #123 
- Blog Posts are functional
    - Create, Update, Get by ID, Get all, Delete
    - Title, Content, Date, 1 to 1 User 
- Blog Thread Views also functional
    -  Create, Update, Get by Post ID, Get by Thread ID
    - Update Title, **Pagination For Threads**
    - 1 to 1 Mapping with cascade on its initial post

![image](https://github.com/user-attachments/assets/db699d27-4ff3-45be-bfec-7df67e1ecd0d)

2024-12-29 00:16 UTC, abdelh17 requested changes
Thread view elements will need to be removed in the next iteration, as discussed on call

2024-12-29 00:28 UTC, abdelh17 requested changes

2024-12-29 00:28 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/dtos/blog/BlogPostRequestDto.java
> +    private Long userId; // User ID creating the blog post
remove userid, the user is fetched from the session

2024-12-29 00:28 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/controllers/BlogPostController.java
> +        BlogPostResponseDto response = blogPostService.create(request);
need to pass in authenticated user to the create function.
Something like : `User poster = SecurityUtil.getAuthenticatedUser();`

2024-12-29 00:28 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/controllers/BlogPostController.java
> +        return blogPostService.findById(id)
don't do the conversion here, do it in the service.

2024-12-29 00:28 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/controllers/BlogPostController.java
> +    public ResponseEntity<BlogPostResponseDto> createBlogPost(@Valid @RequestBody BlogPostRequestDto request) {
is `@Valid` annotation necessary?

2024-12-29 00:28 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/BlogPostServiceImpl.java
> +    private final UserRepository userRepository;
should not have user repository here

2024-12-29 00:28 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/BlogPostServiceImpl.java
> +        User user = userRepository.findById(request.getUserId())
pass user in the function, from the session

2024-12-29 00:28 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/BlogPostServiceImpl.java
> +        BlogPost blogPost = BlogPost.builder()
avoid doing this, look at the following function in ClientWEorkflowServiceImpl
```java
public void createProject(ProjectCreateDto projectCreateDto, User client) {

        Project projectToSave = ProjectCreateDto.toEntity(projectCreateDto);
        projectToSave.setExpirationDate(projectCreateDto.getExpirationDate() != null ? projectCreateDto.getExpirationDate() : LocalDate.now().plusDays(7));
        projectToSave.setClient(client);
        projectService.saveProject(projectToSave);
    }
```

2024-12-29 00:28 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/BlogPostServiceImpl.java
> +        BlogPost blogPost = blogPostRepository.findById(id)
throw new `ApiException` instead of RuntimewException

2024-12-29 00:28 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/services/entity_services/impl/BlogPostServiceImpl.java
> +    public void delete(Long id) {
need to check that the post belongs to the person who deletes. Pass in the user id or the user and do the check.

2024-12-30 02:27 UTC, abdelh17 approved these changes

2024-12-30 02:29 UTC, ChemsCode approved these changes

2024-12-30 02:29 UTC, merged