Ãfeat: #26 implemented class diagram entities
abdelh17/Quolance pull request #35
Opened 2024-10-24 01:25 UTC by OussamaCherifi

Implemented class diagram with existing relations.

2024-10-24 02:10 UTC, abdelh17 requested changes
Save the files that are to be removed on the side, they will be needed later in the project, but not in the near future. Other than that, there are just a few fields missing in a few classes to represent the relationships between classes.

2024-10-24 02:10 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/entities/AssociatedTags.java
remove this file for now

2024-10-24 02:10 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/entities/Project.java
> +    private List<AssociatedTags> associatedTags;
should be `List<Tag>` not `List<AssociatedTags>`

2024-10-24 02:10 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/entities/Project.java
maybe missing link to client( user class), freelancer (user type)

2024-10-24 22:34 UTC, abdelh17 approved these changes

2024-10-24 22:37 UTC, abdelh17 requested changes
Set spring.jpa.hibernate.ddl-auto in application.properties to an environment variable to avoid messing up other DBs when pushing a new value

2024-10-24 22:37 UTC, KA-devl approved these changes

2024-10-24 22:37 UTC, KA-devl commented
lgtm

2024-10-25 00:03 UTC, abdelh17 approved these changes

2024-10-25 00:04 UTC, merged