#27 #7 Created endpoints for get all and get by id
abdelh17/Quolance pull request #40
Opened 2024-10-26 20:07 UTC by NotMalek

2024-10-26 20:17 UTC, abdelh17 requested changes

2024-10-26 20:17 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/controllers/FreelancerController.java
> +        List<ProjectDto> projects = projectService.getAllProjects();
go through FreelancerService

2024-10-26 20:17 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/controllers/FreelancerController.java
> +        ProjectDto project = projectService.getProjectById(id);
go through FreelancerService

2024-10-26 20:32 UTC, abdelh17 approved these changes

2024-10-27 03:21 UTC, KA-devl approved these changes

2024-10-27 17:35 UTC, merged