Feature : A client should be able to post a project
abdelh17/Quolance pull request #68
Opened 2024-10-30 16:49 UTC by KA-devl

As a user of type Client, I should be able to post my project (contract). The form should be displayed in multiple steps, and must be responsive. Below are some pictures 
![image](https://github.com/user-attachments/assets/337b49da-06f6-4ce0-8df2-94a515d774fc)
![image](https://github.com/user-attachments/assets/2e9b2b1e-dada-4355-86c6-1d7e9d2806bf)
![image](https://github.com/user-attachments/assets/d20158e9-9242-4575-9579-a4bb6f2faff5)
![image](https://github.com/user-attachments/assets/b12dfc5b-8deb-4483-9792-4a85b934ad36)
![image](https://github.com/user-attachments/assets/3c9a9f32-3765-47d4-a988-de82499af49b)

2024-11-02 22:18 UTC, ChemsCode approved these changes

2024-11-03 01:30 UTC, ChemsCode submitted a review, later dismissed

2024-11-03 02:03 UTC, abdelh17 requested changes

2024-11-03 02:03 UTC, abdelh17 commented on quolance-api/src/main/resources/application.yml
Dont push ur application.yml

2024-11-03 04:21 UTC, KA-devl commented on quolance-api/src/main/resources/application.yml
nice catch

2024-11-03 04:38 UTC, ChemsCode approved these changes

2024-11-03 17:35 UTC, abdelh17 approved these changes

2024-11-03 19:22 UTC, merged