Bug fixed, added uniqueness constraint
abdelh17/Quolance pull request #79
Opened 2024-11-05 23:43 UTC by NotMalek

2024-11-05 23:58 UTC, abdelh17 requested changes

2024-11-05 23:58 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/entities/Application.java
> +@Table(name = "application",
remove this, it's not necessary

2024-11-05 23:58 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/services/impl/FreelancerServiceImpl.java
> +                .orElseThrow(() -> new RuntimeException("Project not found"));
instead of RuntimeException,  `throw new ApiException("Project not found.");`

2024-11-05 23:58 UTC, abdelh17 commented on quolance-api/src/main/java/com/quolance/quolance_api/services/impl/FreelancerServiceImpl.java
> +            throw new RuntimeException("You have already applied to this project");
like above, use `ApiException`

2024-11-06 00:35 UTC, abdelh17 approved these changes

2024-11-06 00:43 UTC, SSathu approved these changes
Good fix

2024-11-06 00:43 UTC, merged